version: "3"

services:
    VPN_Client1:
        image: handsonsecurity/seed-ubuntu:large
        container_name: client-10.0.3.5
        tty: true
        cap_add:
                - ALL
        extra_hosts:
                - "vpnlabserver.com:10.0.3.8"
        devices:
                - "/dev/net/tun:/dev/net/tun"
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.3.0:
                ipv4_address: 10.0.3.5
        command: bash -c "tail -f /dev/null"
        
    VPN_Client2:
        image: handsonsecurity/seed-ubuntu:large
        container_name: client-10.0.3.6
        tty: true
        cap_add:
                - ALL
        extra_hosts:
                - "vpnlabserver.com:10.0.3.8"
        devices:
                - "/dev/net/tun:/dev/net/tun"
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.3.0:
                ipv4_address: 10.0.3.6
        command: bash -c "tail -f /dev/null"
    
    VPN_Client3:
        image: handsonsecurity/seed-ubuntu:large
        container_name: client-10.0.3.7
        tty: true
        cap_add:
                - ALL
        extra_hosts:
                - "vpnlabserver.com:10.0.3.8"
        devices:
                - "/dev/net/tun:/dev/net/tun"
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.3.0:
                ipv4_address: 10.0.3.7
        command: bash -c "tail -f /dev/null"

    Host_V:
        image: handsonsecurity/seed-ubuntu:large
        container_name: host-192.168.70.101
        tty: true
        cap_add:
                - ALL
        volumes:
                - ./volumes:/volumes
        networks:
            net-192.168.70.0:
                ipv4_address: 192.168.70.101
        command: bash -c "ip route del default  &&
                          ip route add default via 192.168.70.1  &&
                          /etc/init.d/openbsd-inetd start &&
                          tail -f /dev/null"
                
    Router:
        image: handsonsecurity/seed-ubuntu:large
        container_name: server-10.0.3.8-192.168.70.1
        tty: true
        cap_add:
                - ALL
        devices:
                - "/dev/net/tun:/dev/net/tun"
        sysctls:
                - net.ipv4.ip_forward=1
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.0.3.0:
                ipv4_address: 10.0.3.8
            net-192.168.70.0:
                ipv4_address: 192.168.70.1
        command: bash -c "ip route del default  &&
                          ip route add default via 10.0.3.1 &&
                          tail -f /dev/null"
    
networks:
    net-192.168.70.0:
        name: net-192.168.70.0
        ipam:
            config:
                - subnet: 192.168.70.0/24
                  gateway: 192.168.70.100

    net-10.0.3.0:
        name: net-10.0.3.0
        ipam:
            config:
                - subnet: 10.0.3.0/24
                  gateway: 10.0.3.1
